import "server-only";
import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { load } from "cheerio";

type PageRecord = {
  file: string;
  title: string;
  heading: string;
  description: string;
  source: string;
  type: string;
  text: string;
  categories?: string[];
  tags?: string[];
};
type Manifest = { pages: Record<string, PageRecord> };
const contentRoot = path.join(process.cwd(), "content", "aitoolfame");
export async function getReplicaManifest(): Promise<Manifest> {
  return JSON.parse(
    await fs.readFile(path.join(contentRoot, "manifest.json"), "utf8"),
  );
}
async function readPage(page: PageRecord) {
  if (process.env.REPLICA_CONTENT_SOURCE !== "bundled") {
    const route = new URL(page.source).pathname + new URL(page.source).search;
    const id = `replica.page.${createHash("sha256").update(route).digest("hex").slice(0, 32)}`;
    const { sanityClient } = await import("@/sanity/lib/client");
    const html = await sanityClient.fetch<string | null>(
      "*[_id == $id][0].html",
      { id },
      { cache: "no-store" },
    );
    if (!html) throw new Error(`Missing imported page in shopapphub: ${route}`);
    return html;
  }
  if (!/^[a-f0-9]+\.html$/.test(page.file))
    throw new Error("Invalid content file");
  return fs.readFile(path.join(contentRoot, "pages", page.file), "utf8");
}
export async function renderReplica(url: URL) {
  const manifest = await getReplicaManifest();
  const pathname = url.pathname.replace(/\/$/, "") || "/";
  const params = new URLSearchParams(url.search);
  for (const key of Array.from(params.keys()))
    if (!["page", "sort", "f", "category", "tag", "q"].includes(key))
      params.delete(key);
  params.sort();
  const key = pathname + (params.size ? `?${params}` : "");
  const exact = manifest.pages[key];
  const dynamic = params.has("q") || params.has("sort") || params.has("tag");
  if (exact && !dynamic && pathname !== "/search")
    return { html: await readPage(exact), status: 200 };
  const listing =
    pathname === "/category" ||
    pathname === "/tag" ||
    pathname === "/search" ||
    /^\/(category|tag)\/[^/]+$/.test(pathname);
  if (listing) {
    const template =
      (pathname !== "/search" && manifest.pages[pathname]) ||
      manifest.pages["/category"];
    const $ = load(await readPage(template));
    const query = (params.get("q") || "").trim().toLowerCase();
    const selectedTags = (params.get("tag") || "").split(",").filter(Boolean);
    let items = Object.entries(manifest.pages).filter(
      ([route, p]) =>
        /^\/item\/[^/?]+$/.test(route) &&
        (!query ||
          `${p.heading} ${p.description}`.toLowerCase().includes(query)) &&
        (!pathname.startsWith("/category/") ||
          p.categories?.includes(pathname)) &&
        (!pathname.startsWith("/tag/") || p.tags?.includes(pathname)) &&
        selectedTags.every((tag) => p.tags?.includes(`/tag/${tag}`)),
    );
    const cards = JSON.parse(
      await fs.readFile(path.join(contentRoot, "cards.json"), "utf8"),
    ) as Record<string, { html: string; featured: boolean; order: number }>;
    if (params.get("f")?.includes("featured"))
      items = items.filter(([route]) => cards[route]?.featured);
    const sort = params.get("sort") || "time-desc";
    items.sort(([a, pa], [b, pb]) =>
      sort.startsWith("name")
        ? pa.heading.localeCompare(pb.heading) *
          (sort.endsWith("desc") ? -1 : 1)
        : ((cards[a]?.order ?? 9999) - (cards[b]?.order ?? 9999)) *
          (sort.endsWith("asc") ? -1 : 1),
    );
    const perPage = 11;
    const totalPages = Math.max(1, Math.ceil(items.length / perPage));
    const current = Math.min(
      totalPages,
      Math.max(1, Number(params.get("page")) || 1),
    );
    // A stable hook is generated by the normalizer; no layout-specific traversal at runtime.
    const target = $("[data-replica-grid]").first();
    if (!target.length) return { html: await readPage(template), status: 200 };
    const pinned = target
      .children()
      .not("[data-replica-card]")
      .toArray()
      .map((element) => $.html(element))
      .join("");
    const html = items
      .slice((current - 1) * perPage, current * perPage)
      .map(([route]) => cards[route]?.html || "")
      .join("");
    target.html(
      pinned +
        (html ||
          '<p class="col-span-full py-12 text-center text-muted-foreground">No tools found. Try another search or reset your filters.</p>'),
    );
    if (query || pathname === "/search")
      $("main h1")
        .first()
        .text(
          query
            ? `Search results for “${params.get("q")}”`
            : "Discover AI tools",
        );
    $('input[placeholder*="Search"]').attr("value", params.get("q") || "");
    const link = (page: number, label: string) => {
      const next = new URLSearchParams(params);
      next.set("page", String(page));
      return `<a class="replica-page-link${page === current ? " active" : ""}" href="${pathname}?${next.toString().replaceAll("&", "&amp;")}">${label}</a>`;
    };
    $("[aria-label=pagination]").html(
      `${current > 1 ? link(current - 1, "←") : ""}${Array.from(
        { length: totalPages },
        (_, i) => i + 1,
      )
        .filter(
          (n) => n === 1 || n === totalPages || Math.abs(n - current) <= 2,
        )
        .map((n) => link(n, String(n)))
        .join("")}${current < totalPages ? link(current + 1, "→") : ""}`,
    );
    $("head title").text(`${query ? "Search" : "AI Tools"} - AIToolFame`);
    return { html: $.html(), status: 200 };
  }
  const home = load(await readPage(manifest.pages["/"]));
  home("main").html(
    '<section class="container py-24 text-center"><h1 class="text-4xl">Page not found</h1><p class="mt-6">This page is not available.</p><a class="replica-page-link mt-6" href="/">Back to home</a></section>',
  );
  return { html: home.html(), status: 404 };
}
